### ISSUE TITLE
Filter by category

### ISSUE THREAD

**Issue by doug-wade** [Ategon/Lemmy-Mega-Bot#11]
I have [a feed](https://www.sounderatheart.com/latest/rss/) that I am interested in running a bot for, and I would like to post two categories to two different communities -- "Ride of the Valkyries" to lemmy.world/c/reign_fc and everything else, except "Subscriber-only content" to lemmy.world/c/sounders_fc. I don't think from my reading of the comments in `config.yaml`, the bot can support this use case.

I'd like to propose we add a pair of new keys to a `feed` in `config.yaml`, `include_categories` and `exclude_categories`, which take lists of categories which are included in the feed or excluded from the feed, respectively.

For my use case, for example, I would have the following config:

```yaml
feeds:
  example_include:
    include_categories: 
     - "Ride Of The Valkyries"

  example_exclude:
    exclude_categories: 
      - "Ride Of The Valkyries"
      - "Subscriber-only content"
```

If there is interest in this feature, I would be interested in contributing a patch.
