### ISSUE TITLE
Allow customizing rss-parser options

### ISSUE THREAD

**Issue by doug-wade** [Ategon/Lemmy-Mega-Bot#15]
I'm having trouble with some of my rss feeds timing out. I think 1 minute is probably a reasonable default, but for debugging purposes, I'd like to increase it to 2 minutes. Similarly, I'm wondering if passing a custom user-agent string will help.

I'd like to add a new key to `config.yaml` that is the options passed to `rss-parser`. For example

```yaml
parserOptions:
  timeout: 120000
  headers:
    User-Agent: "Mozilla/5.0 (compatible; lemmy-mega-bot/1.0; +https://github.com/Ategon/Lemmy-Mega-Bot)"
```
