### ISSUE TITLE
Error: Bad Request

### ISSUE THREAD

**Issue by QazCetelic** [Ategon/Lemmy-Mega-Bot#26]
Same config as #8 

Using `sh.itjust.works` instance (running 0.18.5).

## stdout
```
STARTED: Started Bot
INSTANCES: 1 instances loaded.
FEEDS: 1 feeds loaded.
Starting bot
Initializing DB
Logging in
DB: Connected to the database.
TABLE: Loaded time table
TABLE: Loaded posts table.
POSTS: 0 posts in database.
Logged in
Marking account as bot account
Error: Bad Request
    at LemmyHttp.<anonymous> (/home/user/Programming/Web/rss-bot/node_modules/lemmy-js-client/dist/http.js:887:19)
    at Generator.throw (<anonymous>)
    at rejected (/home/user/Programming/Web/rss-bot/node_modules/lemmy-js-client/dist/http.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## config.yaml
```yaml
---
# Whether to give the bot a bot tag (true) or not (false). Recommended to mark it but the option is here if you already 
# marked it manually and it starts throwing user_already_exists errors
markAsBot: true

# How often to check for new posts in minutes
postCheckInterval: 10

# How often to check for a new day in minutes (for unpinning posts)
dayCheckInterval: 10

# The timezone to use for the bot (as reference for unpinning posts at midnight)
# You can see the options here: https://www.inmotionhosting.com/support/website/tz-ref-table/
timezone: 'Europe/Amsterdam'

# Posts from how many days ago are you willing to backpost when the bot starts
dayCutOff: 3

# Set to true to add all posts to the db without posting them. Good to set for one run to clear out backposts if you 
# dont want any old posts posted when the bot is first ran. Set to false to post normally
stopPosts: false

# Set to true if you want to see log messages. False if not
# (Note I cant control log messages sent by the bot library so those will still show. Just ones thrown by the bot wont)
showLogs: true

# The maximum amount of posts it will do on every post check. Set to 0 for no limit. (Each post being posted to another instance is separate in here but itll finish up the same post before it stops)
maxPosts: 5

# The time in milliseconds it will sleep before doing another post in the same post check
postSleepDuration: 5000

# The instances and communities used by the bot
instances:
  sh.itjust.works: # The instance name
    nos_tech:
      - "nos_tech"


# The rss feeds used to pull posts from
feeds:
  nos_tech:
    url: 'https://feeds.nos.nl/nosnieuwstech'
    content: 'description'
    datefield: 'pubDate'
```
