### ISSUE TITLE
Bot Unable To Post To Instances

### ISSUE THREAD

**Issue by lerajes** [Ategon/Lemmy-Mega-Bot#5]
Bot acct is on: lemm.ee
Initial error posting to: lemmy.world/c/metal
Second error (after repointing target community) posting to: lemm.ee/c/test

The bot I created ran fine for 2 days then stopped working. After talking with u/Ategon we thought it might be because the instance (lemmy.world) was behind a CloudFlare challenge. I then stopped the bot and edited the settings to point at lemm.ee/c/test which is a Community to test posting for apps and bots. Lemm.ee is *not* using CloudFlare. The bot will still not post to an instance. I use forever (as per the readme) so I have a log of the issue (attached)

[Bb8N.log](https://github.com/Ategon/Lemmy-Mega-Bot/files/12312741/Bb8N.log)

But the error is: `Could not find !test@lemm.ee`

This community definitely exists.

**Comment by Ategon** [comment]
How did you enter the instance + community name in the config file? Thinking this is either an issue with what the bot is using to search or something about how it constructs the allowlist broke

**Comment by lerajes** [comment]
Like this:

```
# The instances and communities used by the bot
instances:
  lemm.ee: # The instance name
    test: # The community slug (value in url) in that instance
      - "amgr" # The feed to use (do a new line with a dash in front for each feed)
```
